# Generated by Django 5.1.3 on 2025-02-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='job_title',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
