# Generated by Django 5.1.3 on 2025-02-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_blog_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='job_title',
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_title',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
